name: hadron projects
on:
  workflow_dispatch

jobs:
  native:
    name: ${{ matrix.project }}/${{ matrix.platform }}/${{ matrix.build }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        build: ['system', 'standalone']
        project:
          - mmomtchev/magickwand.js

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout hadron
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/hadron
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
        working-directory: ${{ github.workspace }}/hadron
      - run: sudo npm link
        working-directory: ${{ github.workspace }}/hadron

      - name: Checkout ${{ matrix.project }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.project }}
          path: ${{ github.workspace }}/project
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: true

      - name: Setup ${{ matrix.project }}
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install

      - name: Link hadron
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm link @mmomtchev/hadron --verbose --foreground-scripts

      - name: Run default build
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: |
          npm install --build-from-source \
            ${{ matrix.build == 'standalone' && '--standalone-build' || '' }} \
            --enable-regenerate
