name: hadron projects
on:
  workflow_dispatch

jobs:
  native:
    name: ${{ matrix.project }} ${{ matrix.platform }} ${{ matrix.build }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - mmomtchev/hadron-swig-napi-example-project
          - mmomtchev/magickwand.js
          - mmomtchev/proj.js
        include:
          - project: mmomtchev/hadron-swig-napi-example-project
            build: system
          - project: mmomtchev/hadron-swig-napi-example-project
            build: standalone
          - project: mmomtchev/magickwand.js
            build: system
          - project: mmomtchev/magickwand.js
            build: standalone
          - project: mmomtchev/proj.js
            build: system

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout ${{ matrix.project }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.project }}
          path: ${{ github.workspace }}/project
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: true

      - name: Setup ${{ matrix.project }}
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install

      - name: Use current hadron (${{ github.ref_name }})
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install git+https://github.com/mmomtchev/hadron-js.git#${{ github.ref_name }}

      - name: Run default build
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: |
          npm install --build-from-source \
            ${{ matrix.build == 'standalone' && '--standalone-build --enable-conan' || '' }} \
            --enable-regenerate
