name: hadron projects
on:
  workflow_dispatch

jobs:
  native:
    name: ${{ matrix.project }} ${{ matrix.platform }} ${{ matrix.build }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - mmomtchev/hadron-swig-napi-example-project
          - mmomtchev/hadron-nobind-example-project
          - mmomtchev/magickwand.js
          - mmomtchev/proj.js
          - mmomtchev/node-ffmpeg
        build:
          - system
          - standalone
        exclude:
          # proj.js does not have a working standalone build yet
          - project: mmomtchev/proj.js
            build: standalone
          # node-ffmpeg does not have a working standalone build yet
          - project: mmomtchev/node-ffmpeg
            build: standalone

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout ${{ matrix.project }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.project }}
          path: ${{ github.workspace }}/project
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: true

      - name: Setup ${{ matrix.project }}
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install --skip-native --skip-wasm

      - name: Use current hadron (${{ github.ref_name }})
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install git+https://github.com/mmomtchev/hadron-js.git#${{ github.ref_name }}

      # Only magickwand.js has --enable/--disable conan options
      # Only the SWIG projects have --enable-regenerate
      - name: Run default build
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: |
          npm install --build-from-source \
            ${{ matrix.build == 'standalone' && '--standalone-build --enable-conan' || '' }} \
            --enable-regenerate \
            --skip-wasm

      - name: Try loading the module
        working-directory: ${{ github.workspace }}/project
        run: node -p "require('.')"


  wasm:
    name: ${{ matrix.project }} WASM
    strategy:
      fail-fast: false
      matrix:
        project:
          - mmomtchev/hadron-swig-napi-example-project
          - mmomtchev/magickwand.js
          - mmomtchev/proj.js

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.8

      - name: Checkout ${{ matrix.project }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.project }}
          path: ${{ github.workspace }}/project
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: true

      - name: Setup ${{ matrix.project }}
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install --skip-native --skip-wasm

      - name: Use current hadron (${{ github.ref_name }})
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install git+https://github.com/mmomtchev/hadron-js.git#${{ github.ref_name }}

      # Only magickwand.js has --enable/--disable conan options
      # Only the SWIG projects have --enable-regenerate
      - name: Run default build
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install --build-wasm-from-source --enable-conan --enable-regenerate --skip-native


  npmrc_options:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout npmrc
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            test/fixtures/magickwand-npmrc/npmrc

      - name: Checkout magickwand.js
        uses: actions/checkout@v4
        with:
          repository: mmomtchev/magickwand.js
          path: ${{ github.workspace }}/project
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: true

      - name: Setup magickwand.js
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install --skip-native --skip-wasm

      - name: Use current hadron (${{ github.ref_name }})
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install git+https://github.com/mmomtchev/hadron-js.git#${{ github.ref_name }}

      - name: Setup npmrc options
        shell: bash
        run: cat test/fixtures/magickwand-npmrc/npmrc >> $HOME/.npmrc

      - name: Run build with npmrc options
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install

      - name: Try loading the module
        working-directory: ${{ github.workspace }}/project
        run: node -p "new (require('.').Magick.CoderInfo)('GIF').name()"

      - name: Ensure that the module has been rebuilt
        working-directory: ${{ github.workspace }}/project
        run: |
          if node -p "new (require('.').Magick.CoderInfo)('PNG').name()"; then
            exit 1
          fi

  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout magickwand.js
        uses: actions/checkout@v4
        with:
          repository: mmomtchev/magickwand.js
          path: ${{ github.workspace }}/project
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: true

      - name: Setup magickwand.js
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install --skip-native --skip-wasm

      - name: Use current hadron (${{ github.ref_name }})
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: npm install git+https://github.com/mmomtchev/hadron-js.git#${{ github.ref_name }}

      - name: Produce a debug build
        shell: bash
        working-directory: ${{ github.workspace }}/project
        run: |
          npx xpm install
          npx xpm install --config native-debug
          npx xpm run generate
          npx xpm run prepare --config native-debug
          npx xpm run build --config native-debug

      - name: Try loading the module
        working-directory: ${{ github.workspace }}/project
        run: node -p "new (require('.').Magick.CoderInfo)('GIF').name()"
